example/blog/urls.py
"""blog Url's file."""

from django.urls import path

from .views import (
    ArticleCreateView,
    all_tags,
    author,
    dashboard,
)

app_name = "blog"
app_label = "blog"


urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("author/", author, name="author"),
    path("all-tags/", all_tags, name="all-tags"),
    path(
        "create/article/", ArticleCreateView.as_view(), name="create-article"
    ),
]

example/core/urls.py
# from allauth import account
from allauth import account
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", account.views.LoginView.as_view(), name="login"),
    path("tag_me/", include("tag_me.urls", namespace="tag_me")),
    path("blog/", include("blog.urls", namespace="blog")),
]


# If we are in DEBUG mode add debug-toolbar to url_patterns.
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
        path("__reload__/", include("django_browser_reload.urls")),
    ]

tag_me/urls.py
"""django-tag-me Url's file."""

from django.urls import path

from .views import (
    MgmtUserTagListView,
    SynchronisedTagFieldListView,
    TagFieldListView,
    TaggedFieldEditView,
    TagManagementView,
    UserTagEditView,
    UserTagListView,
    WidgetAddUserTagView,
)

app_label = "tag_me"
app_name = "tag_me"

urlpatterns: list = []

mgmt_urls = [
    path(
        "mgmt/",
        TagManagementView.as_view(),
        name="tag-mgmt",
    ),
    path(
        "list/tag/",
        MgmtUserTagListView.as_view(),
        name="list-tags",
    ),
    path(
        "tagged-field-edit/<int:pk>/",
        TaggedFieldEditView.as_view(),
        name="tagged-field-edit",
    ),
    path(
        "tagged-field-list/",
        TagFieldListView.as_view(),
        name="tagged-field-list",
    ),
    path(
        "sync-tagged-field-list/",
        SynchronisedTagFieldListView.as_view(),
        name="sync-tagged-field-list",
    ),
]

tag_urls = [
    path(
        "list/tag/<uuid:pk>/",
        UserTagListView.as_view(),
        name="list-user-tags",
    ),
    path(
        "edit/tag/<int:pk>/",
        UserTagEditView.as_view(),
        name="edit-tag",
    ),
    path(
        "add/tag/<int:pk>/",
        WidgetAddUserTagView.as_view(),
        name="add-tag",
    ),
]

urlpatterns.extend(mgmt_urls)
urlpatterns.extend(tag_urls)

example/blog/models.py
"""django-tag-me blog models"""

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import pgettext_lazy as _
from users.models import CustomUser

from tag_me.models.fields import TagMeCharField

User = get_user_model()


class Author(models.Model):
    """Author model"""

    class Meta:
        verbose_name = _(
            "Verbose Name",
            "Author",
        )
        verbose_name_plural = _(
            "Verbose Plural",
            "Authors",
        )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    pen_name = models.CharField(
        max_length=255,
        verbose_name="Author",
    )

    bio = models.TextField(
        blank=True,
        null=True,
        verbose_name="Biography",
    )

    def __str__(self):
        return self.pen_name


class Article(models.Model):
    """Article model"""

    class Meta:
        verbose_name = "Blog Article"
        verbose_name_plural = "Blog Articles"

    class ArticleTags(models.TextChoices):
        """An example using choices to constrain tag list"""

        TWOMINREAD = (
            "2 Min Read",
            _(
                "Article Tag",
                "2 Min Read",
            ),
        )
        FIVEMINREAD = (
            "5 Min Read",
            _(
                "Article Tag",
                "5 Min Read",
            ),
        )

    author = models.ForeignKey(
        "Author",
        on_delete=models.CASCADE,
        verbose_name="Article Author",
    )

    article = models.TextField(
        verbose_name="Article",
    )
    tag = TagMeCharField(
        max_length=255,
        null=True,
        blank=True,
        choices=ArticleTags.choices,
        verbose_name="Article Tag",
        help_text="A tag for the Article",
    )

    user_tag = TagMeCharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name="Article User Tag",
        help_text="A tag for the Article",
    )

    user_tag2 = TagMeCharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name="Article User Tag 2",
        help_text="A tag2 for the Article",
    )

example/users/models.py
"""example project CustomUser Models."""

from django.apps import apps
from django.contrib import auth
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(
        self, username, email, password, **extra_fields
    ):  # pragma: no cover
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError("A username must be supplied.")
        email = self.normalize_email(email)
        if not email:
            raise ValueError(_("An email address must be supplied."))
        if not password:
            raise ValueError(_("A password must be supplied."))
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        username = GlobalUserModel.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)

        return user

    def create_user(
        self, username, email=None, password=None, **extra_fields
    ):  # pragma: no cover
        """
        Create and save a standard user with the supplied username, email, and password.
        """
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(
        self, username, email=None, password=None, **extra_fields
    ):  # pragma: no cover
        """
        Create and save a super user with the supplied username, email, and password.
        """
        extra_fields.setdefault("is_active", True)
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("user_type", "SUPERUSER")

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must be staff."))
        if extra_fields.get("is_active") is not True:
            raise ValueError(_("Superuser must be an active user."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must be a superuser."))
        if extra_fields.get("user_type") != "SUPERUSER":
            raise ValueError(_("Superuser must be type SUPERUSER."))

        return self._create_user(username, email, password, **extra_fields)

    def with_perm(
        self,
        perm,
        is_active=True,
        include_superusers=True,
        backend=None,
        obj=None,
    ):  # pragma: no cover
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    "You have multiple authentication backends configured and "
                    "therefore must provide the `backend` argument."
                )
        elif not isinstance(backend, str):
            raise TypeError(
                "backend must be a dotted import path string (got %r)."
                % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, "with_perm"):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class CustomUser(AbstractUser):
    """Extends the standard User model"""

    objects = CustomUserManager()

    class CustomUserType(models.TextChoices):
        """Custom user type choices"""

        # Change these to suit your needs before initial migration.
        FREE = "FREE", _("Free")
        LEVEL_1 = "LEVEL 1", _("Level 1")
        LEVEL_2 = "LEVEL 2", _("Level 2")
        STAFF = "STAFF", _("Staff")
        SUPERUSER = "SUPERUSER", _("Superuser")

    user_type = models.CharField(
        _("Type"),
        null=False,
        blank=False,
        max_length=50,
        choices=CustomUserType.choices,
        default=CustomUserType.FREE,
        help_text="Displays the users current user type.",
    )
    image_url = models.URLField(
        max_length=250,
        verbose_name=_(
            "Image URL",
        ),
        null=True,
        blank=True,
    )

example/blog/forms.py
"""blog Forms file."""

from django import forms

from tag_me.forms.mixins import TagMeModelFormMixin

from .models import Article


class ArticleCreateForm(TagMeModelFormMixin, forms.ModelForm):
    """Article tags creation form"""

    class Meta:
        model = Article
        fields = "__all__"
        exclude = ["tag", "user_tag2"]


class ArticleUpdateForm(TagMeModelFormMixin, forms.ModelForm):
    """Article tags creation form"""

    class Meta:
        model = Article
        fields = "__all__"

example/users/forms.py
"""example project CustomUser Forms."""

from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.utils.translation import gettext_lazy as _

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """A basic custom user creation form."""

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            "user_type",
            "image_url",
        )

        error_messages = {
            "username": {
                "unique": _(
                    "That user name already exists, please choose another."
                )
            }
        }


class CustomUserChangeForm(UserChangeForm):
    """A basic custom user change form."""

    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            "user_type",
            "image_url",
        )

example/blog/views.py
"""blog Views file."""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from tag_me.views.mixins import TagMeViewMixin
from .forms import (
    ArticleCreateForm,
    ArticleUpdateForm,
)
from .models import Article, Author


class ArticleCreateView(TagMeViewMixin, CreateView):
    """Article tags creation"""

    model = Article
    form_class = ArticleCreateForm
    template_name = "blog/create_article.html"
    success_url = reverse_lazy("blog:user-tags")


def dashboard(request):
    return render(request, "blog/dashboard.html")


def author(request):
    return render(request, "blog/authors.html")


def all_tags(request):
    return render(request, "blog/all_tags.html")


def user_tags(request):
    return render(request, "blog/user_tags.html")

example/users/views.py
"""example project CustomUser Views."""

# from django.shortcuts import render

# Create your views here.

example/templates/blog/all_tags.html
<p>All Tags</p>

example/templates/blog/authors.html
<p>Authors Data</p>

example/templates/blog/create_article.html
{% extends 'base.html' %}
{% block content %}

<p>Create Article</p>
{{form.media}}
{{ csrf_token }}
{{form}}

{% endblock %}

example/templates/blog/create_article_tag.html
{% extends 'base.html' %}
{% block content %}

<p>Create Article Tags</p>
{{form.media}}
{{form}}

{% endblock %}

example/templates/blog/dashboard.html
{% extends "base.html" %}

{% block content %}
<nav class="bg-gray-900" x-data="{ mobileMenuOpen: false, profileMenuOpen: false, currentPath: '{{ request.path }}' }">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <button 
          type="button" 
          class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
          aria-controls="mobile-menu" 
          aria-expanded="false"
          @click="mobileMenuOpen = !mobileMenuOpen" 
        >
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>

          <svg :class="{ 'block': !mobileMenuOpen, 'hidden': mobileMenuOpen }" class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg :class="{ 'block': mobileMenuOpen, 'hidden': !mobileMenuOpen }" class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <a 
              href="{% url 'blog:author' %}" 
              hx-get="{% url 'blog:author' %}"
              hx-target="#htmx-container"
              hx-trigger="click"
              @click="currentPath = '{% url 'blog:author' %}'"
              :class="{ 'bg-gray-800 text-white': currentPath == '{% url 'blog:author' %}', 'bg-gray-900 text-gray-300 hover:bg-gray-700 hover:text-white': currentPath != '{% url 'blog:author' %}' }" 
              class="rounded-md px-3 py-2 text-sm font-medium"
              aria-current="page"
            >
              Author
            </a>
            <a 
              href="{% url 'blog:all-tags' %}" 
              hx-get="{% url 'blog:all-tags' %}"
              hx-target="#htmx-container"
              hx-trigger="click"
              @click="currentPath = '{% url 'blog:all-tags' %}'"
              :class="{ 'bg-gray-800 text-white': currentPath == '{% url 'blog:all-tags' %}', 'bg-gray-900 text-gray-300 hover:bg-gray-700 hover:text-white': currentPath != '{% url 'blog:all-tags' %}' }" 
              class="rounded-md px-3 py-2 text-sm font-medium"
              aria-current="page"
            >
              All Tags
            </a>
            <a 
              hx-get="{% url 'tag_me:list-tags' %}"
              hx-target="#htmx-container"
              hx-trigger="click"
              @click="currentPath = '{% url 'tag_me:list-tags' %}'"
              :class="{ 'bg-gray-800 text-white': currentPath == '{% url 'tag_me:list-tags' %}', 'bg-gray-900 text-gray-300 hover:bg-gray-700 hover:text-white': currentPath != '{% url 'tag_me:list-tags' %}' }" 
              class="rounded-md px-3 py-2 text-sm font-medium"
              class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page"
            >
              User Tags
            </a>
            <a 
              href="{% url 'tag_me:tag-mgmt' %}" 
              @click="currentPath = '{% url 'tag_me:tag-mgmt' %}'"
              :class="{ 'bg-gray-800 text-white': currentPath == '{% url 'tag_me:tag-mgmt' %}', 'bg-gray-900 text-gray-300 hover:bg-gray-700 hover:text-white': currentPath != '{% url 'tag_me:tag-mgmt' %}' }" 
              class="rounded-md px-3 py-2 text-sm font-medium"
              class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page"
            >
              Tag Management
            </a>
            <a 
              href="https://django-tag-me.readthedocs.io/en/latest/?badge=latest" 
              target="_blank"
              class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">
              Tag Me Docs
            </a>
          </div>
        </div>
      </div>

      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <div class="relative ml-3" x-data="{ open: false }">
          <div>
            <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true"
              @click="profileMenuOpen = !profileMenuOpen"
              @click.away="profileMenuOpen = false"
            >
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full" src="{{ user.image_url }}" alt="User Image">
            </button>
          </div>

          <div x-show="profileMenuOpen" class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <a href="{% url 'account_logout' %}" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div :class="{ 'block': mobileMenuOpen, 'hidden': !mobileMenuOpen }" class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <a 
        href="{% url 'blog:author' %}" 
        hx-get="{% url 'blog:author' %}"
        hx-target="#htmx-container"
        hx-trigger="click"
        @click="currentPath = '{% url 'blog:author' %}'"
        :class="{ 'bg-gray-800 text-white': currentPath == '{% url 'blog:author' %}', 'bg-gray-900 text-gray-300 hover:bg-gray-700 hover:text-white': currentPath != '{% url 'blog:author' %}' }" 
        class="rounded-md px-3 py-2 text-sm font-medium"
        aria-current="page"
      >
        Author
      </a>
      <a 
        href="{% url 'blog:all-tags' %}" 
        hx-get="{% url 'blog:all-tags' %}"
        hx-target="#htmx-container"
        hx-trigger="click"
        @click="currentPath = '{% url 'blog:all-tags' %}'"
        :class="{ 'bg-gray-800 text-white': currentPath == '{% url 'blog:all-tags' %}', 'bg-gray-900 text-gray-300 hover:bg-gray-700 hover:text-white': currentPath != '{% url 'blog:all-tags' %}' }" 
        class="rounded-md px-3 py-2 text-sm font-medium"

        aria-current="page"
      >
        All Tags
      </a>
      <a 
        href="{% url 'tag_me:list-tags' %}" 
        hx-get="{% url 'tag_me:list-tags' %}"
        hx-target="#htmx-container"
        hx-trigger="click"
        @click="currentPath = '{% url 'tag_me:list-tags' %}'"
        :class="{ 'bg-gray-800 text-white': currentPath == '{% url 'tag_me:list-tags' %}', 'bg-gray-900 text-gray-300 hover:bg-gray-700 hover:text-white': currentPath != '{% url 'tag_me:list-tags' %}' }" 
        class="rounded-md px-3 py-2 text-sm font-medium"

        aria-current="page"
      >
        User Tags
      </a>
      <a 
        href="https://django-tag-me.readthedocs.io/en/latest/?badge=latest" 
        target="_blank"
        class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">
        Tag Me Docs
      </a>
    </div>
  </div>
</nav>

<div
  id='htmx-container'
  class="pt-6 flex justify-center items center min-w-screen min-h-screen flex dark:bg-gray-900"
>

</div>

{% endblock %}